name: Build and Deploy
on:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master 
env:
  APP_NAME: twilio
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  KUBERNETES_CLUSTER: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_KUBERNETES_CLUSTER || vars.STAGING_KUBERNETES_CLUSTER }}
  KUBERNETES_NAMESPACE: apps
  TWILIO_API_KEY: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_TWILIO_API_KEY || vars.STAGING_TWILIO_API_KEY }}
  TWILIO_SENDER_PHONE_NUMBER: ${{ vars.TWILIO_SENDER_PHONE_NUMBER }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER -o none;

      - name: Deploy Twilio Secret
        shell: pwsh
        run: |
          Get-Content .kubernetes/twilio-auth-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/twilio-auth-secret.tmp.yaml;

          $result = az aks command invoke `
              -g $env:AZURE_GROUP_KUBERNETES `
              -n $env:KUBERNETES_CLUSTER `
              --file .kubernetes/twilio-auth-secret.tmp.yaml `
              --command @"
                  set -eu

                  kubectl apply -f twilio-auth-secret.tmp.yaml || exit 1
          "@ --output json | ConvertFrom-Json;

          echo $result;

          if ($result.exitCode -ne 0)
          {
              throw "error";
          }

